version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_SA_PASSWORD=Cpc33UBI  #user: sa
      - ACCEPT_EULA=Y
    ports:
      - "3433:1433"
    volumes:
      - sqlserver:/var/opt/mssql

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  sqlserver:


# Para utilizar Oracle, basta descomentar as linhas 19-35 (não esqueça de comentar ou apagar a configuração MSSQL - linhas 1-15)
#version: '3'
#services:
#  oracle:
#    image: doctorkirk/oracle-19c
#    mem_limit: 1g
#    cpus: 1
#    environment:
#      - ORACLE_SID=xe
#      - ORACLE_PWD=Cpc33UBI #user: SYSTEM
#    volumes:
#      - oradata:/opt/oracle/oradata
#    ports:
#      - "1521:1521"
#    container_name: db_minishop
#
#volumes:
#  oradata: